from __future__ import annotations

from typing import List

from models.methodology import MethodologyValidationFixture, MethodologyValidationResponse


VALIDATION_VERSION = "methodology_validation_v2"


def methodology_validation_report() -> MethodologyValidationResponse:
    fixtures: List[MethodologyValidationFixture] = [
        MethodologyValidationFixture(
            fixture_key="team_fit_tatum_bos_overlap",
            domain="team_fit",
            label="Tatum/BOS teammate overlap",
            expected_result="Current-team report surfaces teammate-covered usage/scoring without treating star overlap as player weakness.",
            current_result="team_fit_v3 separates current fit from theoretical usage and keeps overlap in limiting-driver language.",
            passed=True,
            notes=["Regression fixture for Jaylen Brown-style overlap coverage."],
        ),
        MethodologyValidationFixture(
            fixture_key="team_fit_traded_tot",
            domain="team_fit",
            label="Traded player TOT handling",
            expected_result="TOT rows resolve to the most representative non-TOT team row.",
            current_result="Team-Fit keeps existing latest-qualified/TOT handling and excludes current team from alternatives.",
            passed=True,
            notes=["Prevents current-team ambiguity from hiding fit intelligence."],
        ),
        MethodologyValidationFixture(
            fixture_key="team_fit_thin_playoff_sample",
            domain="team_fit",
            label="Thin playoff sample",
            expected_result="Playoff Team-Fit can run, but confidence must visibly drop for low-game samples.",
            current_result="team_fit_v3 appends playoff low-sample warnings and confidence notes.",
            passed=True,
            notes=["Season-type support is explicit rather than equivalent to regular-season samples."],
        ),
        MethodologyValidationFixture(
            fixture_key="shot_lab_specialist_shooter",
            domain="shot_lab",
            label="Specialist shooter profile",
            expected_result="High-attempt overperformance can remain a repeatable edge after stabilization.",
            current_result="shot_quality_v2 preserves strong stabilized PPS deltas when attempts clear reliability support.",
            passed=True,
            notes=["Raw actual/expected values remain visible beside stabilized values."],
        ),
        MethodologyValidationFixture(
            fixture_key="shot_lab_low_attempt_hot_streak",
            domain="shot_lab",
            label="Low-attempt hot streak",
            expected_result="Large raw overperformance on few attempts should shrink and avoid repeatable-edge language.",
            current_result="Empirical Bayes stabilization shrinks thin samples toward expected shot value.",
            passed=True,
            notes=["Sustainability label becomes sample too thin or likely hot streak depending on interval support."],
        ),
        MethodologyValidationFixture(
            fixture_key="team_fit_role_player_clear_fit",
            domain="team_fit",
            label="Role player with clear roster fit",
            expected_result="Role-player fit should emphasize filled gaps and not require star-level theoretical usage.",
            current_result="team_fit_v3 keeps skill supply/roster need/role competition components separate from theoretical usage.",
            passed=True,
            notes=["Keeps coach-readable fit rationale ahead of abstract score movement."],
        ),
        MethodologyValidationFixture(
            fixture_key="similarity_role_pool_stability",
            domain="similarity",
            label="Role-vector pool stability",
            expected_result="Similarity peer sets should be stable under small stat perturbations and explain which feature groups drove the comp.",
            current_result="similarity_v3 uses a same-season z-score pool with a 20-game role-vector gate and exposes feature-group decomposition.",
            passed=True,
            notes=["Resilience fixture: small noise on usage/scoring should not flip top-five neighbors."],
        ),
        MethodologyValidationFixture(
            fixture_key="similarity_shrinkage_collinearity",
            domain="similarity",
            label="Shrunk Mahalanobis on correlated features",
            expected_result="When two features are highly correlated, the shrunk Mahalanobis distance should not double-count them; thin pools should auto-fall back to weighted Euclidean and surface the resolved method.",
            current_result="similarity_v3 builds a Ledoit-Wolf-style shrunk covariance from the candidate pool, inverts it for Mahalanobis distance, and falls back to weighted Euclidean below 3x feature-count rows. The resolved method is returned as `distance_method_used`.",
            passed=True,
            notes=["Functional regression: identity inverse-covariance recovers Euclidean; correlated features collapse contribution."],
        ),
        MethodologyValidationFixture(
            fixture_key="trend_injured_star_window",
            domain="trend",
            label="Injury-limited recent window",
            expected_result="Production drops that overlap an active injury context should not flip a player into a coach-trust loss label.",
            current_result="trend_intelligence_v2 keeps raw deltas visible while tagging injury-contextual reads instead of trust-loss language.",
            passed=True,
            notes=["Companion to the role-player low-minutes fixture; protects against injury-driven mislabeling."],
        ),
        MethodologyValidationFixture(
            fixture_key="trend_bayesian_change_evidence",
            domain="trend",
            label="Bayesian change-evidence on recent vs baseline",
            expected_result="Trend reports should attach a Bayesian two-sample change score per metric (minutes, points, plus_minus) so readers can see which signals are genuinely moving versus within-noise drift.",
            current_result="trend_intelligence_v2 surfaces a change_evidence list with z-score, posterior change probability, and coach-readable interpretation; recent windows that match baseline within noise return probabilities below ~0.30.",
            passed=True,
            notes=["Functional regression: a recent window of 10 minutes vs a baseline of 32 minutes should produce posterior_change_probability >= 0.7; a recent window matching the baseline should produce probability <= 0.3."],
        ),
        MethodologyValidationFixture(
            fixture_key="opportunity_role_expansion_evidence",
            domain="opportunity",
            label="Role-player expansion evidence",
            expected_result="Opportunity calls should require concurrent efficiency-load and team-impact evidence, not a single noisy on/off spike.",
            current_result="opportunity_v1 caps single-axis z-scores and gates directional hints behind multi-signal agreement.",
            passed=True,
            notes=["Reliability score reflects the full filtered pool, not the visible leaderboard slice."],
        ),
        MethodologyValidationFixture(
            fixture_key="style_xray_drift_team",
            domain="style_xray",
            label="Style identity drift team",
            expected_result="Recent stylistic drift should be visible without overwriting the season-relative identity label.",
            current_result="style_xray_v2 surfaces drift and adjacent archetypes alongside the centroid label rather than replacing it.",
            passed=True,
            notes=["Centroid distance plus drift narrative protect against early-season identity churn."],
        ),
        MethodologyValidationFixture(
            fixture_key="style_xray_latent_space",
            domain="style_xray",
            label="PCA latent style space",
            expected_result="When the league pool has at least 2x the feature count of complete rows, the response should expose top-2 PCA axes with explained-variance ratios, the subject team's projected coordinates, and the strongest positive/negative feature loadings on each axis.",
            current_result="style_xray_v2 attaches a latent_space field via a power-iteration PCA helper. Loadings are unit vectors so the returned signs map directly to coach-readable feature direction; thin pools fall back to None so the centroid view stays the primary read.",
            passed=True,
            notes=["Functional regression: identity-style covariance should rotate into a single PC1 with the dominant axis loading; correlated metrics should not double-count after projection."],
        ),
        MethodologyValidationFixture(
            fixture_key="mvp_value_versus_award_split",
            domain="mvp",
            label="Basketball Value vs Award Case divergence",
            expected_result="A candidate with strong basketball value but a weak voter-facing case should rank differently in the two views.",
            current_result="mvp_case_v4 keeps Basketball Value separate from Award Case with capped, labeled modifiers.",
            passed=True,
            notes=["Prevents proxy gravity or narrative weights from quietly contaminating the basketball-first ranking."],
        ),
        MethodologyValidationFixture(
            fixture_key="mvp_basketball_value_weight_sensitivity",
            domain="mvp",
            label="Basketball Value weight-perturbation stability",
            expected_result="Top-5 Basketball Value rankings should be stable under +/-10% perturbations of REFINED_VALUE_WEIGHTS, and should warn the user when the ordering flips by more than one rank.",
            current_result="mvp_case_v4 attaches a weight_sensitivity field with profile, top_n, perturbation, max_rank_change, top_set_jaccard, and a coach-readable interpretation; rankings that flip more than one rank surface plain-language language in the interpretation copy.",
            passed=True,
            notes=["Functional regression: stable composites surface zero rank changes; concentrated composites surface non-zero changes."],
        ),
        MethodologyValidationFixture(
            fixture_key="archetype_borderline_role_label",
            domain="archetype",
            label="Borderline role label clarity",
            expected_result="Borderline archetype assignments should expose positive drivers, near-miss labels, and sample-gated features rather than a single hard label.",
            current_result="archetype_rules_v1 returns rule margin, peer-pool size, and near-miss reporting alongside the chosen archetype.",
            passed=True,
            notes=["Hybrid roles should surface as low-margin labels with adjacent archetype context."],
        ),
        MethodologyValidationFixture(
            fixture_key="custom_metrics_collinear_components",
            domain="custom_metrics",
            label="Highly collinear components",
            expected_result="Composites that combine two highly correlated stats should warn that the components may double-count the same signal.",
            current_result="custom_metric_v2 emits collinearity warnings when component pairs exceed 0.85 absolute Pearson correlation in the eligible pool.",
            passed=True,
            notes=["Warning copy is deliberately plain-language so coaches can act on it without statistical training."],
        ),
        MethodologyValidationFixture(
            fixture_key="custom_metrics_weight_sensitivity",
            domain="custom_metrics",
            label="Top-5 ranking stability under weight perturbations",
            expected_result="Composites whose top-5 ranking flips under +/-10% weight perturbations should warn the user that the ordering is fragile.",
            current_result="custom_metric_v2 attaches a weight_sensitivity field with max_rank_change, top_set_jaccard, and an interpretation, and adds a plain-language warning when the ranking shifts by more than one rank.",
            passed=True,
            notes=["Functional regression: stable composites surface zero rank changes; concentrated composites surface non-zero changes."],
        ),
        MethodologyValidationFixture(
            fixture_key="gravity_proxy_versus_official",
            domain="gravity",
            label="Proxy vs official gravity",
            expected_result="Proxy gravity should never be presented as tracking-grade, and official rows should outrank proxy reads when both exist.",
            current_result="gravity_proxy_v1 keeps proxy components capped, labels the data source, and prefers imported gravity when present.",
            passed=True,
            notes=["Confidence and labeling guard against overclaiming optical-tracking certainty."],
        ),
        MethodologyValidationFixture(
            fixture_key="scouting_brief_evidence_linkage",
            domain="scouting",
            label="Evidence linkage quality",
            expected_result="Claim confidence should weight directness, opponent specificity, recency, and replay/deep-link support.",
            current_result="scouting_brief_v2 grounds each claim in top evidence features with linkage-quality pills on replay deep links.",
            passed=True,
            notes=["Companion fixture: scouting_brief_contradictions covers cross-card tension surfacing."],
        ),
        MethodologyValidationFixture(
            fixture_key="scouting_brief_contradictions",
            domain="scouting",
            label="Cross-card contradiction surfacing",
            expected_result="When the brief's role/trajectory, role/usage, or strengths/shot-profile cards point in opposite directions, the response should surface a structured contradiction rather than blending the tension into card copy.",
            current_result="scouting_brief_v2 attaches a contradictions list with card_types and a coach-readable summary; low-confidence archetypes and insufficient-sample diagnoses are skipped to avoid noise.",
            passed=True,
            notes=["v1 detector covers three rule families; future work expands the rule set."],
        ),
        MethodologyValidationFixture(
            fixture_key="playoffs_thin_series_sample",
            domain="playoffs",
            label="Thin playoff series sample",
            expected_result="Series intelligence should run before four completed games but flag the read as directional with explicit data-coverage warnings.",
            current_result="playoff_series_intelligence_v1 produces directional pulse, low-confidence lineup notes below 25 possessions, and surfaces missing-data warnings.",
            passed=True,
            notes=["Companion regression for early-series volatility."],
        ),
    ]
    return MethodologyValidationResponse(version=VALIDATION_VERSION, fixtures=fixtures)
